from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem, EnergyMarket
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions

# This file is generated, DO NOT edit this file!

class MarketServiceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()
        self.esdl_obj_mapping : dict[EsdlId, EnergyMarket]= {}

        
        # Calculation: send_current_day_ahead_price
        self.send_current_day_ahead_price_period_seconds = 900
        send_current_day_ahead_price_inputs = [
        
        ]
        send_current_day_ahead_price_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="EnergyMarket",
                                    output_name="day_ahead_price",
                                    output_unit="EURO/KWh", 
                                    data_type="DOUBLE"),
        ]
        send_current_day_ahead_price_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="send_current_day_ahead_price", 
            inputs=send_current_day_ahead_price_inputs, 
            outputs=send_current_day_ahead_price_outputs, 
            calculation_function=self.send_current_day_ahead_price
        )
        self.add_calculation(send_current_day_ahead_price_information)

    def init_calculation_service(self, energy_system: EnergySystem):
        all_esdl_objs = EsdlHelperFunctions.get_all_esdl_objects_from_type(energy_system.eAllContents(), EnergyMarket)
        for esdl_obj in all_esdl_objs:
            if hasattr(esdl_obj, "id"):
                self.esdl_obj_mapping[esdl_obj.id] = esdl_obj

    
    def send_current_day_ahead_price(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    